"""Initial migration.

Revision ID: 2cf057212e1e
Revises: 
Create Date: 2022-07-05 18:49:19.831736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf057212e1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('software_version', sa.String(), nullable=False),
    sa.Column('wastes_height', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=True),
    sa.Column('micro_controller', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['areas.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permissions',
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_name'], ['permissions.name'], ),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('role_name', 'permission_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('area_code', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['area_code'], ['areas.code'], ),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('basket_section',
    sa.Column('height', sa.SmallInteger(), nullable=False),
    sa.Column('width', sa.SmallInteger(), nullable=False),
    sa.Column('length', sa.SmallInteger(), nullable=False),
    sa.Column('wastes_height', sa.SmallInteger(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.PrimaryKeyConstraint('category', 'basket_id')
    )
    op.create_table('collect',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('DOC', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'basket_id', 'DOC')
    )
    op.create_table('complaint',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('date_of_compliant', sa.DateTime(), nullable=False),
    sa.Column('compliant_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'basket_id', 'date_of_compliant')
    )
    op.create_table('software_versions',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.PrimaryKeyConstraint('version', 'basket_id')
    )
    op.create_table('wastes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('DOC', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id', 'category'], ['basket_section.basket_id', 'basket_section.category'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wastes')
    op.drop_table('software_versions')
    op.drop_table('complaint')
    op.drop_table('collect')
    op.drop_table('basket_section')
    op.drop_table('users')
    op.drop_table('roles_permissions')
    op.drop_table('baskets')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('areas')
    # ### end Alembic commands ###
